spring:
  application:
    name: Project2nd
  config:
    import: optional:file:.env  # file : 파일 import, .env : 파일명
  mail:
    username: ${EMAIL_USER}
    password: ${EMAIL_PASSWORD}


#  jackson:
#    deserialization:
#      fail-on-unknown-properties: false

  datasource:
    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
    url: ${PROD.DB_URL}
    username: ${PROD.DB_USERNAME}
    password: ${PROD.DB_PASSWORD}

  servlet:
    multipart:
      max-file-size: 30MB
      max-request-size: 50MB
  data:
    redis:
      host: localhost
      port: 6379

mybatis:
  mapper-locations: mappers/**/*.xml

springdoc:
  api-docs:
    version: openapi_3_1
  swagger-ui:
    path: /swagger
    operations-sorter: method
    default-model-expand-depth: 10
    default-models-expand-depth: 10
    display-request-duration: true
  cache:
    disabled: true

file:
  directory: ${DEFAULT.FILE_DIRECTORY}


app:
  jwt:
    secret: ${JWT_SECRET}
    header-schema-name: authorization
    token-type: Bearer
    access-token-expiry: 600000
    # 1800000 (ms) : 30분

    # RT(Refresh-Token) - 만료시간(ms) - 15일
    refresh-token-cookie-name: refresh-token
    refresh-token-expiry: 1296000000

management:
  endpoint:
    health:
      show-details: always

  endpoints:
    web:
      exposure:
        include: "*"
  info:
    java:
      enabled: true
    os:
      enabled: true
    env:
      enabled: true
  server:
    port: 8080

---
spring:
  config:
    activate:
      on-profile: prod
  data:
    redis:
      port: 6379
      host: 192.168.0.144
  datasource:
    url: ${PROD.DB_URL}
    username: ${PROD.DB_USERNAME}
    password: ${PROD.DB_PASSWORD}
  jpa:
    open-in-view: false
    properties:
      hibernate:
        cache.use_second_level_cache: false

file:
  directory: ${PROD.FILE_DIRECTORY}

---

spring:
  config:
    activate:
      on-profile: tdd
  datasource:
    url: jdbc:log4jdbc:mariadb://localhost:3306/project2nd2
  sql:
    init:
      mode: always
file:
  directory: ${TDD.FILE_DIRECTORY}